name: CV-Engine CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'
      - 'development'

  push:
    branches:
      - 'main'
      - 'development'

jobs:
  build-multiarch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'

      - name: Login to Azure Container Registry
        uses: docker/login-action@v1
        with:
          registry: oostoregistrypoc2.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_TOKEN }}

      - name: Docker meta
        id: docker_meta_versions # you'll use this in the next step
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            oostoregistrypoc2.azurecr.io/
          # Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm/v7
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta_versions.outputs.tags }}
          labels: ${{ steps.docker_meta_versions.outputs.labels }}


      # - name: Build and test cv-engine
      #   run: |
      #     cd services/cv-engine
      #     go build
      #     go test ./...